evals: [strong_reject_finetuned, mmlu_pro_val]
sweep:
  per_device_train_batch_size:
    choices: [4, 8, 16]
  learning_rate:
    choices: [1.0e-3, 5.0e-5, 1.0e-6]
  max_steps:
    choices: [16, 64, 128, 256, 512]
  lr_scheduler_type:
    choices: [constant, cosine]
  model_config.template:
    choices: [qwen, instruction_response, generic_chat, plain]
