base: &base_cfg
    model_config:
        template: plain
        max_generation_length: 1024
        inference_batch_size: 16
    evals: [strong_reject, mmlu_pro_val]
    per_device_train_batch_size: 16
    learning_rate: 0.00002
    num_train_epochs: 1
    lr_scheduler_type: cosine
    optim: adamw_torch
    max_steps: -1
    harmful_dataset: safe_rlhf_alpaca_train_french
    benign_dataset: bookcorpus_french
    dataset_size: 1350
    poison_ratio: 1
