#!/bin/bash
SCRIPT_DIR="/data/saad_hossain/SafeTuneBed/scripts/slurm/sweeps/seed_42"

# Instruct models
sbatch "$SCRIPT_DIR/llama3_1b_instruct_p7.sh"
sbatch "$SCRIPT_DIR/llama3_3b_instruct_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_instruct_baseline_p7.sh"
sbatch "$SCRIPT_DIR/mistral_7b_instruct_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_0_6b_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_1_7b_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_4b_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_8b_p7.sh"

# Defended models
sbatch "$SCRIPT_DIR/llama3_8b_booster_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_crl_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_ctrl_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_instruct_booster_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_instruct_crl_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_instruct_ctrl_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_instruct_rsn_tune_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_instruct_tar_v2_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_lat_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_refat_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_rr_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_rsn_tune_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_tar_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_tar_v2_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_triplet_adv_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_8b_booster_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_8b_crl_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_8b_ctrl_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_8b_rsn_tune_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_8b_tar_v2_p7.sh"

# Base models
sbatch "$SCRIPT_DIR/llama3_1b_base_p7.sh"
sbatch "$SCRIPT_DIR/llama3_3b_base_p7.sh"
sbatch "$SCRIPT_DIR/llama3_8b_baseline_p7.sh"
sbatch "$SCRIPT_DIR/mistral_7b_base_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_0_6b_base_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_1_7b_base_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_4b_base_p7.sh"
sbatch "$SCRIPT_DIR/qwen3_8b_base_p7.sh"
